# Generated by Django 4.0.5 on 2022-06-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
