# Generated by Django 4.0.5 on 2022-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_review_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
