# Generated by Django 4.0.5 on 2022-07-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Slider',
        ),
    ]
