# Generated by Django 4.0.5 on 2022-07-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
