# Generated by Django 4.0.5 on 2022-07-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
