# Generated by Django 4.0.5 on 2022-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_ratings_remove_review_rating_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
