# Generated by Django 4.0.5 on 2022-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_remove_review_ratings_review_rating_delete_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
