# Generated by Django 4.0.5 on 2022-07-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
