# Generated by Django 4.0.5 on 2022-07-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
