# Generated by Django 4.0.5 on 2022-07-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
