# Generated by Django 4.0.5 on 2022-07-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrder',
            new_name='OrderItem',
        ),
    ]
