# Generated by Django 4.1 on 2022-08-23 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0039_alter_address_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
    ]
