# Generated by Django 4.1 on 2022-08-23 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0040_alter_brand_name_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='town_city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
    ]
