# Generated by Django 4.1 on 2022-08-23 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0041_alter_address_address_alter_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
