# Generated by Django 4.1 on 2022-08-23 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0042_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter Valid Phone Number')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('\\d{6}', 'Enter Valid Pincode')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='town_city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed')]),
        ),
    ]
